// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package mysql

import (
	"database/sql"
)

type Message struct {
	ID       int32
	Name     string
	Email    string
	Content  sql.NullString
	CreateAt sql.NullTime
}
