// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package mysql

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg *CreateMessageParams) error
	GetMessage(ctx context.Context) ([]*Message, error)
}

var _ Querier = (*Queries)(nil)
